### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by borkdude** [simongray/clojure-dsl-resources#1]
Some suggestions. Feel free to leave out any that you don't find relevant.

Clojure parsing:

- https://github.com/clojure/tools.reader
- https://github.com/borkdude/edamame: supports location metadata, configuration (allow everything between EDN and full blown Clojure), GraalVM compatible.

Clojure DSL interpretation:

- https://github.com/borkdude/sci: configurable interpreter for running full blown Clojure or a subset / DSL. GraalVM compatible (suited for building CLIs). Also exposes the reader so you can rewrite expressions before you evaluate them. This trick is used in grasp (see below) to make it aware of namespace aliases while searching code.

Clojure code analysis:

- https://github.com/clojure/tools.analyzer
- https://github.com/clj-kondo/clj-kondo/tree/master/analysis (clj-kondo emits analysis info that clojure-lsp uses)

Clojure code search:

- https://github.com/borkdude/grasp

**Comment by simongray** [comment]
I could've sworn that I added tools.analyzer late yesterday night, but it got lost in the staging area.

I've now also added added tools.reader, edamame, and sci now. Thanks.

**Comment by borkdude** [comment]
Thanks!

> borkdude/sci: A limited dialect of Clojure for a single-purpose, scripted application.

While sci is certainly mostly used for scripting, sci covers pretty much all of Clojure except `deftype` and `definterface` and maybe a few other niche things. But you can restrict the subset via configuration which makes it suitable for DSL interpretation. The goal is to be as compatible with Clojure as possible.

**Comment by simongray** [comment]
The description should ideally be a single sentence that briefly explains what the library does, mainly in the context of what the list is about (DSLs and parsing). How about this?

> borkdude/sci: An interpreted, configurable dialect of Clojure suitable for usage as a DSL.

**Comment by borkdude** [comment]
Done:

> Configurable Clojure interpreter suitable for scripting and Clojure DSLs.
